// Copies the built ABIs into abi/ so consumers (the bridge client, stats) read a committed file
// and CI fails on drift between the sources and what was committed. Each ABI is written twice:
// as JSON for tools, and as a `const` TypeScript module so viem types every call and event.
//   bun scripts/abi.ts
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
mkdirSync(resolve(root, 'abi'), { recursive: true });
for (const [name, file, ident] of [
  ['YacanaPortal', 'YacanaPortal.sol/YacanaPortal.json', 'yacanaPortalAbi'],
  ['YACA', 'YACA.sol/YACA.json', 'yacaAbi'],
] as const) {
  const built = (await Bun.file(resolve(root, 'out', file)).json()) as { abi: unknown[] };
  const json = JSON.stringify(built.abi, null, 2);
  await Bun.write(resolve(root, 'abi', `${name}.json`), `${json}\n`);
  await Bun.write(
    resolve(root, 'abi', `${name}.ts`),
    `// Generated by scripts/abi.ts from the built ${name} artifact; do not edit.\nexport const ${ident} = ${json} as const;\n`,
  );
}
console.log('portal ABIs written to abi/');
