// Turns the soak miners' JSONL reports plus the on-chain epoch history into docs/soak-report.md.
// Rows must belong to the recorded deployment; epochs are limited to the soak's time window.
//   AZTEC_NODE_URL=… bun packages/deploy/scripts/soak-report.ts packages/deploy/target/soak-*.jsonl
import { resolve } from 'node:path';
import { PROFILE } from '../../miner-core/src/generated/params.ts';
import { type EpochRow, epochStats } from './epoch-stats.ts';

interface Row {
  t: string;
  label: string;
  event: string;
  run?: string;
  miner?: string;
  [k: string]: unknown;
}

const repo = resolve(import.meta.dir, '../../..');
const argv = process.argv.slice(2);
// Rows written before the driver stamped `run` / `miner` are accepted only with --legacy-ok.
const legacyOk = argv.includes('--legacy-ok');
const files = argv.filter((a) => !a.startsWith('--'));
if (!files.length) throw new Error('usage: soak-report.ts [--legacy-ok] <soak-*.jsonl>…');
const deployment = (await Bun.file(resolve(repo, `deployments/${PROFILE}.json`)).json()) as {
  miner: string;
  nodeUrl: string;
  deployedAt: string;
};
const rows: Row[] = [];
let legacyRows = 0;
for (const f of files) {
  const text = await Bun.file(resolve(f)).text();
  for (const l of text.split('\n')) {
    if (!l.trim()) continue;
    const row = JSON.parse(l) as Row;
    if (!row.t || Number.isNaN(Date.parse(row.t)) || !row.label || !row.event)
      throw new Error(`${f}: malformed row ${l.slice(0, 80)}`);
    if (row.miner !== deployment.miner) {
      if (row.miner || !legacyOk)
        throw new Error(`${f}: row for deployment ${row.miner ?? '(none)'}, expected ${deployment.miner}`);
      legacyRows++;
    }
    rows.push(row);
  }
}
rows.sort((a, b) => a.t.localeCompare(b.t));
const runs = [...new Set(rows.map((r) => r.run ?? `${r.label} (legacy rows)`))];
const t0 = rows[0]?.t ?? deployment.deployedAt;
const t1 = rows.at(-1)?.t ?? t0;
const from = Math.floor(new Date(t0).getTime() / 1000);
const to = Math.floor(new Date(t1).getTime() / 1000);
const hours = (to - from) / 3600;

// Epochs active in the window: the one open at `from`, then those opened up to `to`. An epoch only
// counts as closed when its close also falls inside the window.
const all = await epochStats(process.env.AZTEC_NODE_URL ?? deployment.nodeUrl, deployment.miner);
const activeAtStart = all.findLastIndex((e) => e.openedAt <= from);
// An epoch still open at the cutoff shows the claim count read now, which may include later claims.
const epochs = all
  .filter((e, i) => i >= Math.max(0, activeAtStart) && e.openedAt <= to)
  .map((e) =>
    e.duration !== null && e.openedAt + e.duration <= to
      ? e
      : { ...e, duration: null, retarget: null, claimsNote: ' (latest, open at cutoff)' },
  );
const closed = epochs.filter((e) => e.duration !== null);
const durations = closed.map((e) => e.duration as number);
const median = (xs: number[]) => {
  const s = [...xs].sort((a, b) => a - b);
  return s.length ? (s[Math.floor((s.length - 1) / 2)] as number) : 0;
};

const labels = [...new Set(rows.map((r) => r.label))];
const count = (label: string, event: string) =>
  rows.filter((r) => r.label === label && r.event === event).length;
const total = (event: string) => labels.reduce((n, l) => n + count(l, event), 0);
const fmtT = (t: string) => t.slice(11, 19);
const steps = rows
  .filter((r) => r.event === 'step')
  .map((r) => `| ${fmtT(r.t)} | ${r.label} | ${r.step} | ${r.threads} |`)
  .join('\n');
const epochTable = epochs
  .map(
    (e: EpochRow & { claimsNote?: string }) =>
      `| ${e.epoch} | ${new Date(e.openedAt * 1000).toISOString().slice(11, 19)} | ${e.claims}${e.claimsNote ?? ''} | ${e.duration === null ? 'open' : `${e.duration} s`} | ${e.retarget === null ? '–' : `×${e.retarget.toFixed(3)}`} | ${e.difficulty.toFixed(1)} |`,
  )
  .join('\n');
const perMiner = labels
  .map((l) => {
    const end = rows.find((r) => r.label === l && r.event === 'end');
    return `| ${l} | ${count(l, 'claim')} | ${count(l, 'reverted')} | ${count(l, 'refused') + count(l, 'stale-before-send')} | ${count(l, 'rotated-account')} | ${count(l, 'roll')} | ${(end?.proofs as number | undefined) ?? '–'} |`;
  })
  .join('\n');
const attempts = rows.filter((r) => r.event === 'attempt').map((r) => r.proveMs as number);

const md = `# Testnet soak report — \`${PROFILE}\` profile

Deployment: \`docs/deployments.md\` (miner \`${deployment.miner}\`), node \`${deployment.nodeUrl}\`.
Window: ${t0} → ${t1} (${hours.toFixed(2)} h wall clock), runs ${runs.map((r) => `\`${r}\``).join(', ')}.
Generated by \`packages/deploy/scripts/soak-report.ts\` from the miners' JSONL reports and the epoch history read
from public storage (\`epoch-stats.ts\`), limited to epochs active in the window; an epoch counts as closed only if
its close is inside the window.${legacyRows ? ` ${legacyRows} rows predate the driver's run/deployment stamps (accepted with --legacy-ok).` : ''}

## Summary

| | |
|---|---|
| Epochs closed in the window | ${closed.length} |
| Epoch duration: median / min / max | ${durations.length ? `${median(durations)} s / ${Math.min(...durations)} s / ${Math.max(...durations)} s` : '–'} (expected 300 s, T_MAX 1200 s) |
| Retarget ratios | ${closed.map((e) => `×${(e.retarget as number).toFixed(2)}`).join(', ')} |
| Accepted claims (all miners) | ${total('claim')} |
| Reverted in public (stale, fee paid) | ${total('reverted')} |
| Refused at simulation / discarded before send | ${total('refused') + total('stale-before-send')} |
| Account rotations after a revert | ${total('rotated-account')} |
| Escape-hatch rolls sent | ${total('roll')} |
| W proof time, native (median of sampled attempts) | ${median(attempts)} ms |

## Hashrate schedule

| time (UTC) | miner | step | threads |
|---|---|---|---|
${steps}

## Per miner

| miner | claims | reverted | refused / discarded | rotations | rolls | proofs |
|---|---|---|---|---|---|---|
${perMiner}

## Epochs

| epoch | opened (UTC) | claims | duration | retarget | difficulty |
|---|---|---|---|---|---|
${epochTable}
`;
await Bun.write(resolve(repo, 'docs/soak-report.md'), md);
console.log(md);
