// Turns the soak miners' JSONL reports plus the on-chain epoch history into docs/soak-report.md.
//   AZTEC_NODE_URL=… bun packages/deploy/scripts/soak-report.ts packages/deploy/target/soak-*.jsonl
import { resolve } from 'node:path';
import { PROFILE } from '../../miner-core/src/generated/params.ts';
import { type EpochRow, epochStats } from './epoch-stats.ts';

interface Row {
  t: string;
  label: string;
  event: string;
  [k: string]: unknown;
}

const repo = resolve(import.meta.dir, '../../..');
const files = process.argv.slice(2);
if (!files.length) throw new Error('usage: soak-report.ts <soak-*.jsonl>…');
const rows: Row[] = [];
for (const f of files) {
  const text = await Bun.file(resolve(f)).text();
  for (const l of text.split('\n')) if (l.trim()) rows.push(JSON.parse(l) as Row);
}
rows.sort((a, b) => a.t.localeCompare(b.t));
const deployment = (await Bun.file(resolve(repo, `deployments/${PROFILE}.json`)).json()) as {
  miner: string;
  nodeUrl: string;
  deployedAt: string;
};
const epochs = await epochStats(process.env.AZTEC_NODE_URL ?? deployment.nodeUrl, deployment.miner);

const labels = [...new Set(rows.map((r) => r.label))];
const count = (label: string, event: string) =>
  rows.filter((r) => r.label === label && r.event === event).length;
const starts = rows.filter((r) => r.event === 'start');
const ends = rows.filter((r) => r.event === 'end');
const t0 = starts[0]?.t ?? deployment.deployedAt;
const t1 = ends.at(-1)?.t ?? rows.at(-1)?.t ?? t0;
const hours = (new Date(t1).getTime() - new Date(t0).getTime()) / 3600_000;
const closed = epochs.filter((e) => e.duration !== null);
const durations = closed.map((e) => e.duration as number);
const median = (xs: number[]) => {
  const s = [...xs].sort((a, b) => a - b);
  return s.length ? (s[Math.floor((s.length - 1) / 2)] as number) : 0;
};
const fmtT = (t: string) => t.slice(11, 19);
const steps = rows
  .filter((r) => r.event === 'step')
  .map((r) => `| ${fmtT(r.t)} | ${r.label} | ${r.step} | ${r.threads} |`)
  .join('\n');
const epochTable = epochs
  .map(
    (e: EpochRow) =>
      `| ${e.epoch} | ${new Date(e.openedAt * 1000).toISOString().slice(11, 19)} | ${e.claims} | ${e.duration === null ? 'open' : `${e.duration} s`} | ${e.retarget === null ? '–' : `×${e.retarget.toFixed(3)}`} | ${e.difficulty.toFixed(1)} |`,
  )
  .join('\n');
const perMiner = labels
  .map(
    (l) =>
      `| ${l} | ${count(l, 'claim')} | ${count(l, 'reverted')} | ${count(l, 'refused') + count(l, 'stale-before-send')} | ${count(l, 'roll')} | ${(rows.find((r) => r.label === l && r.event === 'end')?.proofs as number | undefined) ?? '–'} |`,
  )
  .join('\n');
const attempts = rows.filter((r) => r.event === 'attempt').map((r) => r.proveMs as number);

const md = `# Testnet soak report — \`${PROFILE}\` profile

Deployment: \`docs/deployments.md\` (miner \`${deployment.miner}\`), node \`${deployment.nodeUrl}\`.
Window: ${t0} → ${t1} (${hours.toFixed(2)} h wall clock). Generated by \`packages/deploy/scripts/soak-report.ts\`
from the miners' JSONL reports and the epoch history read from public storage (\`epoch-stats.ts\`).

## Summary

| | |
|---|---|
| Closed epochs | ${closed.length} |
| Epoch duration: median / min / max | ${durations.length ? `${median(durations)} s / ${Math.min(...durations)} s / ${Math.max(...durations)} s` : '–'} (expected 300 s, T_MAX 1200 s) |
| Retarget ratios (closed epochs) | ${closed.map((e) => `×${(e.retarget as number).toFixed(2)}`).join(', ')} |
| Accepted claims (all miners) | ${labels.reduce((n, l) => n + count(l, 'claim'), 0)} |
| Reverted in public (stale, fee paid) | ${labels.reduce((n, l) => n + count(l, 'reverted'), 0)} |
| Refused at simulation / discarded before send | ${labels.reduce((n, l) => n + count(l, 'refused') + count(l, 'stale-before-send'), 0)} |
| Escape-hatch rolls sent | ${labels.reduce((n, l) => n + count(l, 'roll'), 0)} |
| W proof time, native (median of sampled attempts) | ${median(attempts)} ms |

## Hashrate schedule

| time (UTC) | miner | step | threads |
|---|---|---|---|
${steps}

## Per miner

| miner | claims | reverted | refused / discarded | rolls | proofs |
|---|---|---|---|---|---|
${perMiner}

## Epochs

| epoch | opened (UTC) | claims | duration | retarget | difficulty |
|---|---|---|---|---|---|
${epochTable}
`;
await Bun.write(resolve(repo, 'docs/soak-report.md'), md);
console.log(md);
