// Writes the selected profile of elixir.params.json into every place a parameter is consumed:
// the miner contract's Noir globals, the work circuit's chain length and miner-core's TS
// constants. Everything generated is committed and diffed in CI, so the config is the single
// source of truth.  ELIXIR_PROFILE=testnet|mainnet bun scripts/params-codegen.ts
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import config from '../elixir.params.json';

const repo = resolve(import.meta.dir, '..');
const profile = process.env.ELIXIR_PROFILE ?? 'testnet';
const p = config.profiles[profile as keyof typeof config.profiles];
if (!p) throw new Error(`unknown profile ${profile}; have ${Object.keys(config.profiles).join(', ')}`);
if (p.T_MAX !== 4 * p.EXPECTED_EPOCH_SECONDS) throw new Error('T_MAX must be 4 × EXPECTED_EPOCH_SECONDS');
if (p.EXPECTED_EPOCH_SECONDS <= 0 || p.EXPECTED_EPOCH_SECONDS >= 2 ** 17)
  throw new Error('EXPECTED_EPOCH_SECONDS out of range');
const target = BigInt(p.INITIAL_TARGET);
if (target <= 0n || target >= 1n << 128n) throw new Error('INITIAL_TARGET must be in (0, 2^128)');
const header = `// Generated by scripts/params-codegen.ts from elixir.params.json (profile ${profile}) — do not edit.`;

const minerNr = `${header}
pub global N: u32 = ${p.N};
pub global EXPECTED_EPOCH_SECONDS: u64 = ${p.EXPECTED_EPOCH_SECONDS};
pub global T_MAX: u64 = ${p.T_MAX};
pub global REWARD: u128 = ${p.REWARD};
pub global VERSION: Field = ${p.VERSION};
`;
const workNr = `${header}
pub global CHAIN_LEN: u32 = ${p.CHAIN_LEN};
`;
const ts = `${header}
export const PROFILE = '${profile}';
export const PARAMS = {
  N: ${p.N},
  EXPECTED_EPOCH_SECONDS: ${p.EXPECTED_EPOCH_SECONDS}n,
  T_MAX: ${p.T_MAX}n,
  REWARD: ${p.REWARD}n,
  DECIMALS: ${p.DECIMALS},
  INITIAL_TARGET: ${target}n,
  GENESIS_SEED: ${BigInt(p.GENESIS_SEED)}n,
  CHAIN_LEN: ${p.CHAIN_LEN},
  VERSION: ${p.VERSION}n,
  TOKEN_NAME: '${p.TOKEN_NAME}',
  TOKEN_SYMBOL: '${p.TOKEN_SYMBOL}',
} as const;
`;
const out: [string, string][] = [
  ['packages/contracts/elixir_miner/src/params.nr', minerNr],
  ['packages/work-circuit/crates/elixir_work/src/params.nr', workNr],
  ['packages/miner-core/src/generated/params.ts', ts],
];
for (const [file, text] of out) {
  mkdirSync(resolve(repo, file, '..'), { recursive: true });
  await Bun.write(resolve(repo, file), text);
}
console.log(`params: profile ${profile} → ${out.map(([f]) => f).join(', ')}`);
