// Writes the selected profile of elixir.params.json into every place a parameter is consumed:
// the miner contract's Noir globals, the work circuit's chain length, the domain separators
// shared by the Noir crates and miner-core, and miner-core's TS constants. It also turns the
// pinned cross-language vectors (packages/work-circuit/fixtures/vectors.json, written by
// packages/miner-core/scripts/pin-vectors.ts) into Noir tests, so the contract checks the same
// hashes miner-core checks. Everything generated is committed and diffed in CI.
//   ELIXIR_PROFILE=testnet|mainnet bun scripts/params-codegen.ts
import { existsSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import config from '../elixir.params.json';

const repo = resolve(import.meta.dir, '..');
const profile = process.env.ELIXIR_PROFILE ?? 'testnet';
const p = config.profiles[profile as keyof typeof config.profiles];
if (!p) throw new Error(`unknown profile ${profile}; have ${Object.keys(config.profiles).join(', ')}`);
if (p.T_MAX !== 4 * p.EXPECTED_EPOCH_SECONDS) throw new Error('T_MAX must be 4 × EXPECTED_EPOCH_SECONDS');
if (p.EXPECTED_EPOCH_SECONDS <= 0 || p.EXPECTED_EPOCH_SECONDS >= 2 ** 17)
  throw new Error('EXPECTED_EPOCH_SECONDS out of range');
if (p.CLAIM_TTL_SECONDS <= 0 || p.CLAIM_TTL_SECONDS >= 86400)
  throw new Error('CLAIM_TTL_SECONDS must be within (0, MAX_TX_LIFETIME = 86400)');
if (p.LAUNCH_NOTICE_SECONDS < 0 || p.LAUNCH_NOTICE_SECONDS >= 2 ** 31)
  throw new Error('LAUNCH_NOTICE_SECONDS out of range');
const target = BigInt(p.INITIAL_TARGET);
if (target <= 0n || target >= 1n << 128n) throw new Error('INITIAL_TARGET must be in (0, 2^128)');
const header = `// Generated by scripts/params-codegen.ts from elixir.params.json (profile ${profile}) — do not edit.`;

// A domain separator is its ASCII tag read as a big-endian integer; tags are 1–31 bytes.
const domainValue = (tag: string): bigint => {
  const bytes = new TextEncoder().encode(tag);
  if (bytes.length === 0 || bytes.length > 31) throw new Error(`domain tag ${tag} must be 1–31 bytes`);
  return bytes.reduce((acc, b) => (acc << 8n) | BigInt(b), 0n);
};
const domains = Object.entries(config.domains).map(([name, tag]) => ({
  name: `DOM_${name}`,
  tag,
  value: domainValue(tag),
}));

const minerNr = `${header}
pub global N: u32 = ${p.N};
pub global EXPECTED_EPOCH_SECONDS: u64 = ${p.EXPECTED_EPOCH_SECONDS};
pub global T_MAX: u64 = ${p.T_MAX};
pub global CLAIM_TTL_SECONDS: u64 = ${p.CLAIM_TTL_SECONDS};
pub global LAUNCH_NOTICE_SECONDS: u64 = ${p.LAUNCH_NOTICE_SECONDS};
pub global REWARD: u128 = ${p.REWARD};
pub global VERSION: Field = ${p.VERSION};
`;
const workNr = `${header}
pub global CHAIN_LEN: u32 = ${p.CHAIN_LEN};
`;
const domainsNr = `${header}
${domains.map((d) => `pub global ${d.name}: Field = 0x${d.value.toString(16)}; // "${d.tag}"`).join('\n')}
`;
const ts = `${header}
export const PROFILE = '${profile}';
export const PARAMS = {
  N: ${p.N},
  EXPECTED_EPOCH_SECONDS: ${p.EXPECTED_EPOCH_SECONDS}n,
  T_MAX: ${p.T_MAX}n,
  CLAIM_TTL_SECONDS: ${p.CLAIM_TTL_SECONDS}n,
  LAUNCH_NOTICE_SECONDS: ${p.LAUNCH_NOTICE_SECONDS}n,
  REWARD: ${p.REWARD}n,
  DECIMALS: ${p.DECIMALS},
  INITIAL_TARGET: ${target}n,
  GENESIS_SEED: ${BigInt(p.GENESIS_SEED)}n,
  CHAIN_LEN: ${p.CHAIN_LEN},
  VERSION: ${p.VERSION}n,
  TOKEN_NAME: '${p.TOKEN_NAME}',
  TOKEN_SYMBOL: '${p.TOKEN_SYMBOL}',
} as const;
/** Domain separators: the ASCII tag as a big-endian field element; identical to the Noir globals. */
export const DOMAINS = {
${domains.map((d) => `  ${d.name}: 0x${d.value.toString(16)}n, // "${d.tag}"`).join('\n')}
} as const;
`;

interface Vectors {
  fixtureProof: string[];
  digest: string;
  low128: string;
  deployDomain: { chainId: string; rollupVersion: string; miner: string; version: string; value: string };
  secretCommitment: { secret: string; recipient: string; value: string };
  nullifier: string;
  nextSeed: { seed: string; nextEpoch: string; now: string; value: string };
  retarget: { expectedEpochSeconds: number; target: string; actual: string; value: string };
}

// The Noir side asserts the values miner-core pinned; either implementation drifting fails its tests.
function vectorsNr(v: Vectors): string {
  const retarget =
    v.retarget.expectedEpochSeconds === p.EXPECTED_EPOCH_SECONDS
      ? `    assert_eq(next_target(${v.retarget.target}, ${v.retarget.actual}), ${v.retarget.value});`
      : `    // pinned for EXPECTED_EPOCH_SECONDS = ${v.retarget.expectedEpochSeconds}; this profile differs`;
  return `${header}
// Cross-language vectors pinned by packages/miner-core/scripts/pin-vectors.ts (vectors.json).
use crate::retarget::next_target;
use crate::ticket::{low128, ticket_digest};
use elixir_work_lib::{DOM_DEPLOY, DOM_NULL, DOM_SECRET, DOM_SEED};
use poseidon::poseidon2::Poseidon2;

global FIXTURE_PROOF: [Field; ${v.fixtureProof.length}] = [
${v.fixtureProof.map((f) => `    ${f},`).join('\n')}
];

#[test]
fn ticket_digest_matches_miner_core() {
    assert_eq(ticket_digest(FIXTURE_PROOF), ${v.digest});
}

#[test]
fn low128_matches_miner_core() {
    assert_eq(low128(${v.digest}), ${v.low128});
}

#[test]
fn deploy_domain_matches_miner_core() {
    let d = v_deploy();
    assert_eq(d, ${v.deployDomain.value});
}

fn v_deploy() -> Field {
    Poseidon2::hash(
        [
            DOM_DEPLOY,
            ${v.deployDomain.chainId},
            ${v.deployDomain.rollupVersion},
            ${v.deployDomain.miner},
            ${v.deployDomain.version},
        ],
        5,
    )
}

#[test]
fn secret_commitment_matches_miner_core() {
    let c = Poseidon2::hash([DOM_SECRET, ${v.secretCommitment.secret}, ${v.secretCommitment.recipient}], 3);
    assert_eq(c, ${v.secretCommitment.value});
}

#[test]
fn ticket_nullifier_matches_miner_core() {
    assert_eq(Poseidon2::hash([DOM_NULL, ${v.digest}], 2), ${v.nullifier});
}

#[test]
fn next_seed_matches_miner_core() {
    let s = Poseidon2::hash(
        [DOM_SEED, ${v.nextSeed.seed}, ${v.nextSeed.nextEpoch}, ${v.digest}, ${v.nextSeed.now}],
        5,
    );
    assert_eq(s, ${v.nextSeed.value});
}

#[test]
fn retarget_matches_miner_core() {
${retarget}
}
`;
}

const out: [string, string][] = [
  ['packages/contracts/elixir_miner/src/params.nr', minerNr],
  ['packages/work-circuit/crates/elixir_work/src/params.nr', workNr],
  ['packages/work-circuit/crates/lib/src/domains.nr', domainsNr],
  ['packages/miner-core/src/generated/params.ts', ts],
];
const vectorsFile = resolve(repo, 'packages/work-circuit/fixtures/vectors.json');
if (existsSync(vectorsFile)) {
  out.push([
    'packages/contracts/elixir_miner/src/test/vectors.nr',
    vectorsNr((await Bun.file(vectorsFile).json()) as Vectors),
  ]);
} else {
  console.warn(
    'params: no vectors.json yet — run bun packages/miner-core/scripts/pin-vectors.ts, then codegen again',
  );
}
for (const [file, text] of out) {
  mkdirSync(resolve(repo, file, '..'), { recursive: true });
  await Bun.write(resolve(repo, file), text);
}
console.log(`params: profile ${profile} → ${out.map(([f]) => f).join(', ')}`);
