// Export the work circuit's VK (115 fields) and VK hash from bb's binary output into the Noir
// globals the verifier crates embed and a TS module for miner-core. The VK is the puzzle: any
// change here means a new deployment, so both outputs are committed and diffed in CI.
//   bun packages/work-circuit/scripts/export-vk.ts [crate]
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { $ } from 'bun';
import { BB, repoRoot, workCircuitRoot } from './toolchain.ts';

const crate = process.argv[2] ?? 'yacana_work';
const dir = resolve(workCircuitRoot, 'target', crate);
await $`${BB} write_vk -b ${workCircuitRoot}/target/${crate}.json --scheme ultra_honk -t noir-recursive-no-zk -o ${dir}`
  .cwd(workCircuitRoot)
  .quiet();
const vk = new Uint8Array(await Bun.file(`${dir}/vk`).arrayBuffer());
const vkHash = new Uint8Array(await Bun.file(`${dir}/vk_hash`).arrayBuffer());
if (vk.length !== 115 * 32) throw new Error(`vk is ${vk.length} bytes, expected 115 × 32`);
if (vkHash.length !== 32) throw new Error(`vk_hash is ${vkHash.length} bytes, expected 32`);

const hex = (bytes: Uint8Array) => `0x${Buffer.from(bytes).toString('hex')}`;
const fields: string[] = [];
for (let i = 0; i < 115; i++) fields.push(hex(vk.subarray(i * 32, i * 32 + 32)));
const hash = hex(vkHash);

const noir = `// Generated by scripts/export-vk.ts from target/${crate}/vk — do not edit.
pub global W_VK: [Field; 115] = [
${fields.map((f) => `    ${f},`).join('\n')}
];
pub global W_VK_HASH: Field = ${hash};
`;
const ts = `// Generated by scripts/export-vk.ts from target/${crate}/vk — do not edit.
export const W_VK: readonly string[] = [
${fields.map((f) => `  '${f}',`).join('\n')}
];
export const W_VK_HASH = '${hash}';
`;
mkdirSync(resolve(workCircuitRoot, 'crates', 'verify_w', 'src'), { recursive: true });
mkdirSync(resolve(workCircuitRoot, 'src', 'generated'), { recursive: true });
// Every embedded copy of the VK is written from this one run; CI diffs them against the commit.
await Bun.write(resolve(workCircuitRoot, 'crates', 'verify_w', 'src', 'vk.nr'), noir);
await Bun.write(resolve(repoRoot, 'packages', 'contracts', 'yacana_spike', 'src', 'vk.nr'), noir);
await Bun.write(resolve(repoRoot, 'packages', 'contracts', 'yacana_miner', 'src', 'vk.nr'), noir);
await Bun.write(resolve(workCircuitRoot, 'src', 'generated', 'vk.ts'), ts);
// The committed fixture: the proof of Prover.toml's inputs, used by the layout, digest and
// mutation tests so they never depend on a prover being available. The proof itself is only
// refreshed when a prove (sweep.ts) has produced one, and whatever ends up committed must verify
// under the VK exported here, or the pinned vectors describe a proof no circuit can satisfy.
const fixtures = resolve(workCircuitRoot, 'fixtures', crate);
mkdirSync(fixtures, { recursive: true });
for (const f of ['proof', 'public_inputs', 'vk', 'vk_hash']) {
  if (await Bun.file(`${dir}/${f}`).exists()) await Bun.write(`${fixtures}/${f}`, Bun.file(`${dir}/${f}`));
}
const verified =
  await $`${BB} verify -p ${fixtures}/proof -i ${fixtures}/public_inputs -k ${fixtures}/vk --scheme ultra_honk -t noir-recursive-no-zk`
    .cwd(workCircuitRoot)
    .nothrow()
    .quiet();
if (verified.exitCode !== 0)
  throw new Error(
    `${fixtures}/proof does not verify under the exported VK; re-prove with sweep.ts --runs 1 ${crate}`,
  );
console.log(`W_VK_HASH = ${hash}; fixtures → ${fixtures}`);
