// Export the work circuit's VK (115 fields) and VK hash from bb's binary output into the Noir
// globals the verifier crates embed and a TS module for miner-core. The VK is the puzzle: any
// change here means a new deployment, so both outputs are committed and diffed in CI.
//   bun packages/work-circuit/scripts/export-vk.ts [crate]
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { workCircuitRoot } from './toolchain.ts';

const crate = process.argv[2] ?? 'elixir_work';
const dir = resolve(workCircuitRoot, 'target', crate);
const vk = new Uint8Array(await Bun.file(`${dir}/vk`).arrayBuffer());
const vkHash = new Uint8Array(await Bun.file(`${dir}/vk_hash`).arrayBuffer());
if (vk.length !== 115 * 32) throw new Error(`vk is ${vk.length} bytes, expected 115 × 32`);
if (vkHash.length !== 32) throw new Error(`vk_hash is ${vkHash.length} bytes, expected 32`);

const hex = (bytes: Uint8Array) => `0x${Buffer.from(bytes).toString('hex')}`;
const fields: string[] = [];
for (let i = 0; i < 115; i++) fields.push(hex(vk.subarray(i * 32, i * 32 + 32)));
const hash = hex(vkHash);

const noir = `// Generated by scripts/export-vk.ts from target/${crate}/vk — do not edit.
pub global W_VK: [Field; 115] = [
${fields.map((f) => `    ${f},`).join('\n')}
];
pub global W_VK_HASH: Field = ${hash};
`;
const ts = `// Generated by scripts/export-vk.ts from target/${crate}/vk — do not edit.
export const W_VK: readonly string[] = [
${fields.map((f) => `  '${f}',`).join('\n')}
];
export const W_VK_HASH = '${hash}';
`;
mkdirSync(resolve(workCircuitRoot, 'crates', 'verify_w', 'src'), { recursive: true });
mkdirSync(resolve(workCircuitRoot, 'src', 'generated'), { recursive: true });
await Bun.write(resolve(workCircuitRoot, 'crates', 'verify_w', 'src', 'vk.nr'), noir);
await Bun.write(resolve(workCircuitRoot, 'src', 'generated', 'vk.ts'), ts);
// The committed fixture: the proof of Prover.toml's inputs, used by the layout, digest and
// mutation tests so they never depend on a prover being available.
const fixtures = resolve(workCircuitRoot, 'fixtures', crate);
mkdirSync(fixtures, { recursive: true });
for (const f of ['proof', 'public_inputs', 'vk', 'vk_hash'])
  await Bun.write(`${fixtures}/${f}`, Bun.file(`${dir}/${f}`));
console.log(`W_VK_HASH = ${hash}; fixtures → ${fixtures}`);
